---
version: 2
updates:
  - package-ecosystem: github-actions
    open-pull-requests-limit: 10
    directory: /
    schedule:
      time: "16:00"
      interval: daily
    allow:
      - dependency-type: all
    assignees:
      - tr3mor
    labels:
      - dependencies
      - actions
  - package-ecosystem: terraform
    open-pull-requests-limit: 10
    directory: terraform/tf-cloud/workspaces/
    schedule:
      time: "16:00"
      interval: daily
    allow:
      - dependency-type: all
    assignees:
      - tr3mor
    labels:
      - dependencies
      - terraform
  - package-ecosystem: terraform
    open-pull-requests-limit: 10
    directory: terraform-modules/tf-cloud/tf-cloud-workspace/
    schedule:
      time: "16:00"
      interval: daily
    allow:
      - dependency-type: all
    assignees:
      - tr3mor
    labels:
      - dependencies
      - terraform
  - package-ecosystem: terraform
    open-pull-requests-limit: 10
    directory: terraform/grafana-cloud/grafana-oncall/
    schedule:
      time: "16:00"
      interval: daily
    allow:
      - dependency-type: all
    assignees:
      - tr3mor
    labels:
      - dependencies
      - terraform
  - package-ecosystem: terraform
    open-pull-requests-limit: 10
    directory: terraform/grafana-cloud/stack/
    schedule:
      time: "16:00"
      interval: daily
    allow:
      - dependency-type: all
    assignees:
      - tr3mor
    labels:
      - dependencies
      - terraform
  - package-ecosystem: gomod
    open-pull-requests-limit: 10
    directory: /
    schedule:
      time: "16:00"
      interval: daily
    allow:
      - dependency-type: all
    assignees:
      - tr3mor
    labels:
      - dependencies
      - golang
