kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: kube-prometheus-stack
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  project: main
  source:
    path: ""
    chart: prometheus-operator-crds
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 5.1.0
  syncPolicy:
    automated:
      selfHeal: true
      allowEmpty: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
