apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: traefik
    server: "https://kubernetes.default.svc"
  project: main
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: 39.0.7
  syncPolicy:
    automated:
      selfHeal: true
      allowEmpty: true
      prune: true
    syncOptions:
      - CreateNamespace=true
