apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: am-routing-tree
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  project: main
  source:
    repoURL: https://github.com/tr3mor/personal-infra.git
    targetRevision: HEAD
    path: "k8s/manifests/am-routing-tree/"
  syncPolicy:
    automated:
      selfHeal: true
      allowEmpty: true
      prune: true
    syncOptions:
      - CreateNamespace=true
