apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: cnpg-system
    server: "https://kubernetes.default.svc"
  project: main
  source:
    path: ""
    chart: cloudnative-pg
    repoURL: https://cloudnative-pg.github.io/charts
    targetRevision: 0.28.0
  syncPolicy:
    automated:
      selfHeal: true
      allowEmpty: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
