apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  project: main
  source:
    path: ""
    chart: postgresql
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 16.7.21
    helm:
      values: |-
        global:
          postgresql:
            auth:
              username: "grafana"
              database: "grafana"
              existingSecret: "local-grafana"
              secretKeys:
                userPasswordKey: "GF_DATABASE_PASSWORD"
                adminPasswordKey: "GF_DATABASE_PASSWORD"
  syncPolicy:
    automated:
      selfHeal: true
      allowEmpty: true
      prune: true
    syncOptions:
      - CreateNamespace=true
