---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: am-routing-tree-prometheus-docs
  labels:
    app.kubernetes.io/name: prometheus-docs
    app.kubernetes.io/instance: am-routing-tree
---
apiVersion: v1
kind: Service
metadata:
  name: am-routing-tree-prometheus-docs
  labels:
    app.kubernetes.io/name: prometheus-docs
    app.kubernetes.io/instance: am-routing-tree
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: prometheus-docs
    app.kubernetes.io/instance: am-routing-tree
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: am-routing-tree-prometheus-docs-rewrite
  labels:
    app.kubernetes.io/name: prometheus-docs
    app.kubernetes.io/instance: am-routing-tree
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-docs
      app.kubernetes.io/instance: am-routing-tree
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus-docs
        app.kubernetes.io/instance: am-routing-tree
    spec:
      serviceAccountName: am-routing-tree-prometheus-docs
      containers:
        - name: prometheus-docs
          image: "tr3mor1401/am-routing-tree:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: am-routing-tree-prometheus-docs
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /webtools/alerting/routing-tree-editor/
    nginx.ingress.kubernetes.io/use-regex: "true"
  labels:
    app.kubernetes.io/name: prometheus-docs
    app.kubernetes.io/instance: am-routing-tree
spec:
  ingressClassName: nginx
  rules:
    - host: "am-routing-tree.localdev"
      http:
        paths:
          - path: /$
            pathType: ImplementationSpecific
            backend:
              service:
                name: am-routing-tree-prometheus-docs
                port:
                  number: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/instance: am-routing-tree
    app.kubernetes.io/name: prometheus-docs
  name: am-routing-tree-prometheus-docs-prefix
spec:
  ingressClassName: nginx
  rules:
    - host: am-routing-tree.localdev
      http:
        paths:
          - backend:
              service:
                name: am-routing-tree-prometheus-docs
                port:
                  number: 3000
            path: /(.+)
            pathType: Prefix
