name: gomod testing
on: # yamllint disable-line rule:truthy
  pull_request:
    paths-ignore:
      - go.mod
jobs:
  gomod_testing:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'
