name: golangci-lint
on:  # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - '**.go'
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.0
          args: --timeout=3m
