---
name: Terraform lint
on:  # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - '**.tf'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Install terraform
        uses: hashicorp/setup-terraform@v3.1.2
      - name: Install tflint
        uses: terraform-linters/setup-tflint@v4
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Terraform format
        run: terraform fmt -check -diff -recursive
      - name: Run tflint
        run: |
          tflint --init
          TF_DIRS=$(find . -name "*.tf" -not -path "./.git/*" -exec dirname {} \; | sort | uniq)
          failed=false
          for dir in $TF_DIRS; do
              echo "tflint $dir"
              tflint --chdir "$dir" -f compact || failed=true;
          done
          if $failed
          then
              exit 1
            else
              exit 0
          fi
