---
name: Terraform - unittest
on:  # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - terraform-modules/**
jobs:
  tf_unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
      - name: Get changed files in the modules folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v46
        with:
          dir_names: "true"
          dir_names_max_depth: "3"
          files: |
            terraform-modules/**
      - name: Install terraform
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: hashicorp/setup-terraform@v3.1.2
      - name: Install go
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Install packages
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: go mod tidy
      - name: Perform unittest
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        env:
          TFE_TOKEN: ${{ secrets.TFE_TOKEN }}
          OAUTH_TOKEN_ID: ${{ secrets.OAUTH_TOKEN_ID }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          for file in ${{ steps.changed-files-specific.outputs.all_changed_files }}; do
            go test -v -timeout 30m ./$file/tests/
          done
