---
name: Terraform - Unittests
on:  # yamllint disable-line rule:truthy
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Get changed files in the docs folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v35
        with:
          dir_names: "true"
          dir_names_max_depth: "3"
          files: |
            terraform-modules/**
      - name: Install terraform
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: hashicorp/setup-terraform@v2.0.3
      - name: Install go
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: Install packages
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: go mod tidy
      - name: Perform unittest
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        env:
          TFE_TOKEN: ${{ secrets.TFE_TOKEN }}
          OAUTH_TOKEN_ID: ${{ secrets.OAUTH_TOKEN_ID }}
        run: |
          for file in ${{ steps.changed-files-specific.outputs.all_changed_files }}; do
            go test -v -timeout 30m ./$file/test/
          done
